packages:
  - "api"
  - "frontend"
  - "library"

catalog:
  # dependencies
  "@aptos-labs/ts-sdk": "^1.27.0"
  "@aptos-labs/wallet-adapter-ant-design": "^3.0.10"
  "@aptos-labs/wallet-adapter-core": "^4.14.0"
  "@aptos-labs/wallet-adapter-react": "^3.5.0"
  "@chakra-ui/icons": "^2.1.1"
  "@chakra-ui/react": "^2.8.2"
  "@emotion/react": "^11.11.1"
  "@emotion/styled": "^11.11.0"
  "@identity-connect/wallet-adapter-plugin": "^1.2.5"
  "@pontem/wallet-adapter-plugin": "^0.2.1"
  "@tanstack/react-query": "^5.8.7"
  "@tsoa/runtime": "^5.0.0"
  "@vitejs/plugin-react": "^4.2.0"
  "buffer": "^6.0.3"
  "express": "^4.18.2"
  "graphql-request": "=5.1.0"
  "petra-plugin-wallet-adapter": "^0.4.5"
  "react": "^18.2.0"
  "react-colorful": "^5.6.1"
  "react-dom": "^18.2.0"
  "react-hook-form": "^7.48.2"
  "react-icons": "^4.12.0"
  "react-router-dom": "^6.20.0"
  "swagger-ui-express": "^5.0.0"
  "tsoa": "^5.1.1"

  # devDependencies
  "@graphql-codegen/cli": "^5.0.0"
  "@graphql-codegen/import-types-preset": "^2.2.6"
  "@graphql-codegen/typescript": "^2.8.8"
  "@graphql-codegen/typescript-graphql-request": "^4.5.9"
  "@graphql-codegen/typescript-operations": "^2.5.13"
  "@types/chroma-js": "^2.4.3"
  "@types/express": "^4.17.21"
  "@types/jest": "^29.5.10"
  "@types/node": "^20.10.0"
  "@types/react": "^18.2.38"
  "@types/react-dom": "^18.2.17"
  "@types/swagger-ui-express": "^4.1.6"
  "@typescript-eslint/eslint-plugin": "^6.12.0"
  "@typescript-eslint/parser": "^6.12.0"
  "dotenv": "^16.3.1"
  "eslint": "^8.54.0"
  "eslint-config-airbnb-base": "^15.0.0"
  "eslint-config-airbnb-typescript": "^17.1.0"
  "eslint-config-react-app": "^7.0.1"
  "eslint-config-prettier": "^9.0.0"
  "eslint-plugin-import": "^2.29.0"
  "jest": "^29.7.0"
  "prettier": "^3.1.0"
  "ts-jest": "^29.1.1"
  "ts-loader": "^9.5.1"
  "ts-node": "^10.9.1"
  "tsup": "^7.2.0"
  "typescript": "=5.1.3"
  "vite": "^4.5.0"
