name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build web and upload the artifact.
  build_web:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4

    # Install pnpm
    - uses: pnpm/action-setup@v4

    # Install deps. and build.
    - run: pnpm install --frozen-lockfile
    - run: cd library && pnpm install --frozen-lockfile
    - run: cd frontend && pnpm install --frozen-lockfile

    # Build the library and the frontend.
    - run: cd library && pnpm build
    - run: cd frontend && CI= pnpm build

    # Upload the artifact.
    - uses: actions/upload-pages-artifact@v1
      with:
        path: frontend/build

  # Deploy web using the artifact from the previous job.
  deploy_web:
    runs-on: ubuntu-latest
    needs: [build_web]
    concurrency: ci-${{ github.ref }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/configure-pages@v1
    - id: deployment
      uses: actions/deploy-pages@v1

  # Build and push Docker image for the API server.
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: api/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
