name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  # Build the library and run the tests.
  build_library:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4

    # Install pnpm
    - run: npm install -g corepack@latest
    - run: corepack enable pnpm

    # Install deps and build.
    - run: cd library && pnpm install
    - run: cd library && pnpm build

    # Run the tests. For now we run the e2e tests even though they could be flaky
    # because they rely on remote APIs.
    - run: cd library && pnpm e2e-test
